### ISSUE TITLE
Google Colab example does not work like how it is suppose too.

### ISSUE THREAD

**Issue by sdf94** [molmod/openmm-tutorial-msbs#1] opened 2020-04-20 01:18 UTC
I have been trying to run the example to run openmm in google colab. Unfortunately, this example does not work. 

The following example however does work: https://gist.github.com/jaimergp/45015e75b4ae5f79a03d24e53b74ac1a 

Could you please update as necessary?

**Comment by tovrstra** [comment] 2020-05-06 15:13
I could not reproduce your problem. When I repeat the instructions in the following notebook, it all works:

https://github.com/molmod/openmm-tutorial-msbs/blob/master/03_elsewhere/02_run_openmm_on_google_colab.ipynb

In summary, if I put the following in a code cell on Google Colab, I get a working OpenMM installation:

```
# Install OpenMM
import sys
print(sys.version)
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local
!conda config --set always_yes yes
!conda config --add channels omnia
!conda config --add channels conda-forge
!conda create -n openmm python=3.6 openmm
import sys
sys.path.append('/usr/local/envs/openmm/lib/python3.6/site-packages')
import simtk.testInstallation
simtk.testInstallation.main()
```

I'm going to close this issue for now. If you still have this issue, please provide more details, e.g. by including steps on how to reproduce it and an error message yout get. I'd be happy to help further.

**Closed by tovrstra** 2020-05-06 15:13 UTC
